# Generated by Django 5.0.2 on 2024-02-26 05:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('album', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(max_length=200, unique=True)),
                ('album_picture', models.ImageField(upload_to=None)),
                ('album_description', models.TextField(max_length=50000)),
                ('artist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('playlist_picture', models.ImageField(upload_to=None)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AlbumInPlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='album.album')),
                ('playlist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.playlist')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=500)),
                ('song_image', models.ImageField(blank=True, null=True, upload_to='image')),
                ('song_discription', models.TextField(blank=True, max_length=100000, null=True)),
                ('audio', models.FileField(blank=True, null=True, upload_to='audio')),
                ('video', models.FileField(blank=True, null=True, upload_to='video')),
                ('audio_duration', models.PositiveIntegerField(default=0)),
                ('genre', models.CharField(choices=[('Rock', 'Rock'), ('Jazz', 'Jazz'), ('EDM', 'EDM'), ('Pop', 'Pop'), ('Dubstep', 'Dubstep'), ('Disco', 'Disco'), ('Techno', 'Techno'), ('Hard Rock', 'Hard Rock'), ('Jungle Music', 'Jungle Music'), ('Classical', 'Classical'), ('Blues', 'Blues'), ('Other', 'Other')])),
                ('lyrics', models.TextField(blank=True, max_length=100000, null=True)),
                ('credits', models.CharField(blank=True, max_length=10000, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('album_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='album.album')),
                ('artist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SongsInAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.album')),
                ('song_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.song')),
            ],
        ),
        migrations.CreateModel(
            name='SongsInPlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.playlist')),
                ('song_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.song')),
            ],
        ),
    ]
