# Generated by Django 5.0.2 on 2024-02-27 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(max_length=200, unique=True)),
                ('album_description', models.TextField(max_length=50000)),
                ('album_picture', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_name', models.CharField(max_length=50)),
                ('playlist_picture', models.ImageField(upload_to=None)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=500)),
                ('song_image', models.URLField(blank=True, null=True)),
                ('song_description', models.TextField(blank=True, max_length=100000, null=True)),
                ('audio', models.URLField(blank=True, null=True)),
                ('video', models.URLField(blank=True, null=True)),
                ('audio_duration', models.PositiveIntegerField(default=0)),
                ('genre', models.CharField(choices=[('Rock', 'Rock'), ('Jazz', 'Jazz'), ('EDM', 'EDM'), ('Pop', 'Pop'), ('Dubstep', 'Dubstep'), ('Disco', 'Disco'), ('Techno', 'Techno'), ('Hard Rock', 'Hard Rock'), ('Jungle Music', 'Jungle Music'), ('Classical', 'Classical'), ('Blues', 'Blues'), ('Other', 'Other')])),
                ('lyrics', models.TextField(blank=True, max_length=100000, null=True)),
                ('credits', models.CharField(blank=True, max_length=10000, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SongsInAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SongsInPlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
