# Generated by Django 5.0.2 on 2024-02-26 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='songs/audio'),
        ),
        migrations.AlterField(
            model_name='song',
            name='song_image',
            field=models.ImageField(blank=True, null=True, upload_to='songs/image'),
        ),
        migrations.AlterField(
            model_name='song',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='songs/video'),
        ),
    ]
