# Generated by Django 5.0.2 on 2024-02-27 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='song_image',
            new_name='song_picture',
        ),
    ]