# Generated by Django 5.0.2 on 2024-02-26 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_alter_song_audio_alter_song_song_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='audio',
        ),
        migrations.RemoveField(
            model_name='song',
            name='song_image',
        ),
        migrations.RemoveField(
            model_name='song',
            name='video',
        ),
    ]
