# Generated by Django 5.0.2 on 2024-02-26 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_song_audio_song_song_image_song_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albuminplaylist',
            name='album_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.album'),
        ),
        migrations.AlterField(
            model_name='song',
            name='album_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.album'),
        ),
    ]
