# Generated by Django 5.0.2 on 2024-02-29 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_alter_song_song_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='audio_duration',
            field=models.PositiveIntegerField(),
        ),
    ]
