# Generated by Django 5.0.2 on 2024-03-01 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_alter_song_audio_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='playlist_picture',
            field=models.URLField(blank=True, null=True),
        ),
    ]
