# Generated by Django 5.0.2 on 2024-02-26 09:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_alter_album_album_picture'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='title',
            new_name='playlist_name',
        ),
        migrations.RemoveField(
            model_name='album',
            name='album_picture',
        ),
        migrations.RemoveField(
            model_name='song',
            name='album_id',
        ),
        migrations.AddField(
            model_name='album',
            name='album_picture_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterUniqueTogether(
            name='playlist',
            unique_together={('user_id', 'playlist_name')},
        ),
        migrations.AlterUniqueTogether(
            name='songsinalbum',
            unique_together={('album_id', 'song_id')},
        ),
        migrations.AlterUniqueTogether(
            name='songsinplaylist',
            unique_together={('playlist_id', 'song_id')},
        ),
        migrations.DeleteModel(
            name='AlbumInPlaylist',
        ),
    ]
