# Generated by Django 5.0.2 on 2024-02-26 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_rename_title_playlist_playlist_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='album_picture_url',
        ),
        migrations.AddField(
            model_name='album',
            name='album_picture',
            field=models.ImageField(blank=True, null=True, upload_to='album/images/'),
        ),
    ]
