# Generated by Django 5.0.2 on 2024-03-01 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_alter_playlist_playlist_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songsinalbum',
            name='song_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='music.song'),
        ),
    ]
