# Generated by Django 5.0.2 on 2024-03-04 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_recentsongs'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recentsongs',
            unique_together=set(),
        ),
    ]
