# Generated by Django 5.0.2 on 2024-03-18 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0012_alter_song_audio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('genre', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('genre_picture', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='song',
            name='genre',
            field=models.CharField(choices=[('Rock', 'Rock'), ('Jazz', 'Jazz'), ('EDM', 'EDM'), ('Pop', 'Pop'), ('Dubstep', 'Dubstep'), ('Disco', 'Disco'), ('Techno', 'Techno'), ('Hard Rock', 'Hard Rock'), ('Jungle Music', 'Jungle Music'), ('Classical', 'Classical'), ('Blues', 'Blues'), ('Other', 'Other')], default=None),
        ),
    ]
