# Generated by Django 5.0.2 on 2024-03-18 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0013_genre_alter_song_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='genre',
            field=models.ForeignKey(blank=True, default='Other', null=True, on_delete=django.db.models.deletion.SET_NULL, to='music.genre'),
        ),
    ]
