# Generated by Django 5.0.2 on 2024-03-27 05:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0015_currentlyplaying'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currentlyplaying',
            name='id',
        ),
        migrations.AlterField(
            model_name='currentlyplaying',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]


# 0017_playlist_is_global
# # Generated by Django 5.0.2 on 2024-03-19 05:56

# from django.db import migrations, models


# class Migration(migrations.Migration):

#     dependencies = [
#         ('music', '0016_remove_currentlyplaying_id_and_more'),
#     ]

#     operations = [
#         migrations.AddField(
#             model_name='playlist',
#             name='is_global',
#             field=models.BooleanField(default=False),
#         ),
#     ]
