# Generated by Django 5.0.2 on 2024-06-01 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0016_remove_currentlyplaying_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='is_global',
            field=models.BooleanField(default=False),
        ),
    ]
