# Generated by Django 5.0.2 on 2024-06-01 20:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('music', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Colab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.URLField()),
                ('video', models.URLField(blank=True, null=True)),
                ('colab_picture', models.URLField(blank=True, null=True)),
                ('audio_duration', models.CharField(default=0, max_length=200)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('colab_name', models.CharField(default='colab', max_length=255)),
                ('song_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.song')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
