# Generated by Django 5.0.2 on 2024-03-06 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colab', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colab',
            old_name='song_description',
            new_name='colab_description',
        ),
        migrations.RenameField(
            model_name='colab',
            old_name='song_name',
            new_name='colab_name',
        ),
        migrations.RemoveField(
            model_name='colab',
            name='song_picture',
        ),
    ]
