# Generated by Django 5.0.2 on 2024-02-29 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colab', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colab',
            name='audio_duration',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
