# Generated by Django 5.0.2 on 2024-03-06 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colab', '0002_rename_song_description_colab_colab_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colab',
            name='colab_description',
        ),
        migrations.AddField(
            model_name='colab',
            name='colab_picture',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='colab',
            name='audio',
            field=models.URLField(null=True),
        ),
    ]
