# Generated by Django 5.0.2 on 2024-02-29 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colab', '0002_alter_colab_audio_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colab',
            name='audio_duration',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='colab',
            name='colab_audio',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='colab',
            name='colab_pic',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='colab',
            name='colab_video',
            field=models.URLField(blank=True, null=True),
        ),
    ]
