# Generated by Django 5.0.2 on 2024-03-04 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colab', '0002_rename_user_id_colab_artist_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='colab',
            name='song_description',
            field=models.CharField(default='this is my colab', max_length=255),
        ),
        migrations.AddField(
            model_name='colab',
            name='song_name',
            field=models.CharField(default='colab', max_length=255),
        ),
    ]
