# Generated by Django 5.0.2 on 2024-02-29 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colab', '0003_alter_colab_audio_duration_alter_colab_colab_audio_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colab',
            old_name='colab_pic',
            new_name='colab_picture',
        ),
    ]
