# Generated by Django 5.0.2 on 2024-03-04 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colab', '0003_colab_song_description_colab_song_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colab',
            old_name='artist_id',
            new_name='user_id',
        ),
    ]
