# Generated by Django 5.0.2 on 2024-02-29 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colab', '0004_rename_colab_pic_colab_colab_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colab',
            old_name='colab_audio',
            new_name='audio',
        ),
    ]
