# Generated by Django 5.0.2 on 2024-02-29 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colab', '0005_rename_colab_audio_colab_audio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colab',
            old_name='audio',
            new_name='colab_audio',
        ),
    ]
