# Generated by Django 5.0.2 on 2024-02-26 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_followers'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='followers',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='Avatar/'),
        ),
    ]
