# Generated by Django 5.0.2 on 2024-03-04 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_delete_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_deactivation',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
