# Generated by Django 5.0.2 on 2024-03-07 05:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_mailotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailotp',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
