# Generated by Django 5.0.2 on 2024-03-08 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_mailotp_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('offline', 'offline'), ('online', 'online')], default='offline'),
        ),
    ]
