# Generated by Django 5.0.2 on 2024-06-01 08:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_user_is_verified_mailverificationtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailverificationtoken',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verifiaction_token', to=settings.AUTH_USER_MODEL),
        ),
    ]
