# Generated by Django 5.0.2 on 2024-03-01 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_songlikes'),
        ('music', '0009_alter_songsinalbum_song_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songlikes',
            name='song_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.song'),
        ),
    ]
